import { z } from 'zod';

import { FailureClass, SecurityScope, STEP_VERBS } from './security.js';

const StepVerbSchema = z.enum(STEP_VERBS);

const TaskEventBase = {
  task_id: z.string().min(1).describe('Owning task id.'),
  at: z.string().datetime().describe('ISO-8601 UTC timestamp.'),
} as const;

export const HandoffReason = z
  .enum(['captcha', 'mfa', 'unexpected_state', 'other'])
  .describe('Reason human intervention is required.');

export type HandoffReason = z.infer<typeof HandoffReason>;

export const TaskEvent = z
  .discriminatedUnion('kind', [
    z.object({
      ...TaskEventBase,
      kind: z.literal('task_queued').describe('Task was queued.'),
    }),
    z.object({
      ...TaskEventBase,
      kind: z.literal('task_started').describe('Task execution started.'),
    }),
    z.object({
      ...TaskEventBase,
      kind: z.literal('step_started').describe('A step execution started.'),
      step_id: z.string().min(1).describe('Step id.'),
      step_type: StepVerbSchema.describe('Step type.'),
    }),
    z.object({
      ...TaskEventBase,
      kind: z.literal('step_retry').describe('A step execution retried.'),
      step_id: z.string().min(1).describe('Step id.'),
      attempt: z.number().int().positive().describe('Retry attempt count.'),
      reason: FailureClass.describe('Retry reason class.'),
    }),
    z.object({
      ...TaskEventBase,
      kind: z.literal('step_completed').describe('A step execution completed.'),
      step_id: z.string().min(1).describe('Step id.'),
      capture_keys: z.array(z.string()).describe('Capture keys produced by the step.'),
    }),
    z.object({
      ...TaskEventBase,
      kind: z.literal('checkpoint_saved').describe('Checkpoint persisted after a step.'),
      after_step_id: z.string().min(1).describe('Last successful step id.'),
    }),
    z.object({
      ...TaskEventBase,
      kind: z.literal('human_handoff_requested').describe('Run paused for human handoff.'),
      step_id: z.string().min(1).describe('Step requiring handoff.'),
      reason: HandoffReason.describe('Reason handoff is required.'),
    }),
    z.object({
      ...TaskEventBase,
      kind: z.literal('task_completed').describe('Task execution completed successfully.'),
      outputs_keys: z.array(z.string()).describe('Output keys generated by the task.'),
    }),
    z.object({
      ...TaskEventBase,
      kind: z.literal('task_failed').describe('Task execution failed.'),
      failure_class: FailureClass.describe('Failure class.'),
      report_path: z.string().min(1).describe('Path to generated report artifact.'),
    }),
    z.object({
      ...TaskEventBase,
      kind: z.literal('validation_failed').describe('Plan or workflow validation failed.'),
      path: z.string().min(1).describe('JSON pointer path for failure.'),
      message: z.string().min(1).describe('Validation failure message.'),
    }),
    z.object({
      ...TaskEventBase,
      kind: z.literal('scope_violation').describe('Scope policy violation detected.'),
      scope: SecurityScope.describe('Effective scope at violation time.'),
      attempted_verb: StepVerbSchema.describe('Attempted step type.'),
      step_id: z.string().min(1).describe('Step id causing violation.'),
    }),
    z.object({
      ...TaskEventBase,
      kind: z.literal('task_resumed').describe('A previously paused or failed run was resumed.'),
      original_run_id: z.string().min(1).describe('The run id of the original run being resumed.'),
      resume_step_id: z.string().min(1).describe('Step id from which execution resumes.'),
    }),
    z.object({
      ...TaskEventBase,
      kind: z
        .literal('chrome_drift_warning')
        .describe('Chrome major version differs from recording.'),
      recorded_chrome_major: z
        .number()
        .int()
        .positive()
        .describe('Chrome major at recording time.'),
      current_chrome_major: z.number().int().positive().describe('Chrome major at run time.'),
      drift: z.number().int().describe('Absolute difference in major versions.'),
    }),
  ])
  .describe('Discriminated union for task lifecycle events.');

export type TaskEvent = z.infer<typeof TaskEvent>;
