import { z } from 'zod';

import { ConfirmationRequest } from './confirmation.js';
import { DiscoveryCycle, DiscoveryOutcome } from './discovery.js';
import { FailureClass, SecurityScope, STEP_VERBS } from './security.js';

const StepVerbSchema = z.enum(STEP_VERBS);

const TaskEventBase = {
  task_id: z.string().min(1).describe('Owning task id.'),
  at: z.string().datetime().describe('ISO-8601 UTC timestamp.'),
} as const;

export const HandoffReason = z
  .enum(['captcha', 'mfa', 'unexpected_state', 'other'])
  .describe('Reason human intervention is required.');

export type HandoffReason = z.infer<typeof HandoffReason>;

export const TaskEvent = z
  .discriminatedUnion('kind', [
    z.object({
      ...TaskEventBase,
      kind: z.literal('task_queued').describe('Task was queued.'),
    }),
    z.object({
      ...TaskEventBase,
      kind: z.literal('task_started').describe('Task execution started.'),
    }),
    z.object({
      ...TaskEventBase,
      kind: z.literal('step_started').describe('A step execution started.'),
      step_id: z.string().min(1).describe('Step id.'),
      step_type: StepVerbSchema.describe('Step type.'),
    }),
    z.object({
      ...TaskEventBase,
      kind: z.literal('step_retry').describe('A step execution retried.'),
      step_id: z.string().min(1).describe('Step id.'),
      attempt: z.number().int().positive().describe('Retry attempt count.'),
      reason: FailureClass.describe('Retry reason class.'),
    }),
    z.object({
      ...TaskEventBase,
      kind: z.literal('step_completed').describe('A step execution completed.'),
      step_id: z.string().min(1).describe('Step id.'),
      capture_keys: z.array(z.string()).describe('Capture keys produced by the step.'),
    }),
    z.object({
      ...TaskEventBase,
      kind: z
        .literal('llm_step_skipped')
        .describe(
          'An llm_summarize step passed its input through unchanged because no model was configured.',
        ),
      step_id: z.string().min(1).describe('Step id that was passed through.'),
      output_as: z.string().min(1).describe('Capture key the raw input was bound to.'),
      reason: z.string().min(1).describe('Why the model path was unavailable.'),
    }),
    z.object({
      ...TaskEventBase,
      kind: z.literal('checkpoint_saved').describe('Checkpoint persisted after a step.'),
      after_step_id: z.string().min(1).describe('Last successful step id.'),
    }),
    z.object({
      ...TaskEventBase,
      kind: z.literal('human_handoff_requested').describe('Run paused for human handoff.'),
      step_id: z.string().min(1).describe('Step requiring handoff.'),
      reason: HandoffReason.describe('Reason handoff is required.'),
    }),
    z.object({
      ...TaskEventBase,
      kind: z.literal('task_completed').describe('Task execution completed successfully.'),
      outputs_keys: z.array(z.string()).describe('Output keys generated by the task.'),
    }),
    z.object({
      ...TaskEventBase,
      kind: z.literal('task_failed').describe('Task execution failed.'),
      failure_class: FailureClass.describe('Failure class.'),
      report_path: z.string().min(1).describe('Path to generated report artifact.'),
    }),
    z.object({
      ...TaskEventBase,
      kind: z.literal('validation_failed').describe('Plan or workflow validation failed.'),
      path: z.string().min(1).describe('JSON pointer path for failure.'),
      message: z.string().min(1).describe('Validation failure message.'),
    }),
    z.object({
      ...TaskEventBase,
      kind: z.literal('scope_violation').describe('Scope policy violation detected.'),
      scope: SecurityScope.describe('Effective scope at violation time.'),
      attempted_verb: StepVerbSchema.describe('Attempted step type.'),
      step_id: z.string().min(1).describe('Step id causing violation.'),
    }),
    z.object({
      ...TaskEventBase,
      kind: z.literal('task_resumed').describe('A previously paused or failed run was resumed.'),
      original_run_id: z.string().min(1).describe('The run id of the original run being resumed.'),
      resume_step_id: z.string().min(1).describe('Step id from which execution resumes.'),
    }),
    z.object({
      ...TaskEventBase,
      kind: z
        .literal('chrome_drift_warning')
        .describe('Chrome major version differs from recording.'),
      recorded_chrome_major: z
        .number()
        .int()
        .positive()
        .describe('Chrome major at recording time.'),
      current_chrome_major: z.number().int().positive().describe('Chrome major at run time.'),
      drift: z.number().int().describe('Absolute difference in major versions.'),
    }),
    z.object({
      ...TaskEventBase,
      kind: z
        .literal('synthesis_completed')
        .describe('The synthesize stage produced a Brief (FEAT-014).'),
      strategy: z
        .enum(['deterministic', 'llm'])
        .describe('Synthesis strategy that produced the Brief.'),
      sources_in: z
        .number()
        .int()
        .nonnegative()
        .describe('Number of extracted sources fed into synthesis.'),
      sources_used: z
        .number()
        .int()
        .nonnegative()
        .describe('Number of deduplicated numbered sources in the Brief.'),
      coverage: z
        .number()
        .min(0)
        .max(1)
        .nullable()
        .describe('Fraction of sources represented in the Brief (0-1), or null.'),
      citation_verdict: z
        .object({
          claims_checked: z.number().int().nonnegative().describe('Claims inspected.'),
          flagged: z.number().int().nonnegative().describe('Claims flagged as unanchored.'),
          stripped: z.number().int().nonnegative().describe('Claims stripped as unanchored.'),
        })
        .describe('Citation-faithfulness verdict from the validator.'),
    }),
    z.object({
      ...TaskEventBase,
      kind: z
        .literal('research_hop_completed')
        .describe('One deep-research hop finished (FEAT-017).'),
      hop_index: z.number().int().positive().describe('1-based hop index.'),
      queries: z.array(z.string()).describe('Queries issued this hop.'),
      docs_fetched: z
        .number()
        .int()
        .nonnegative()
        .describe('Documents successfully fetched+extracted this hop.'),
      docs_kept: z
        .number()
        .int()
        .nonnegative()
        .describe('Documents kept after dedup/diversification this hop.'),
      coverage: z.number().min(0).max(1).describe('Coverage score after this hop (0-1).'),
      coverage_delta: z
        .number()
        .describe('Change in coverage vs the previous hop (may be negative).'),
    }),
    z.object({
      ...TaskEventBase,
      kind: z
        .literal('confirmation_requested')
        .describe('Executor paused for human consent before a flagged step (FEAT-019).'),
      request: ConfirmationRequest.describe('The structured confirmation request.'),
    }),
    z.object({
      ...TaskEventBase,
      kind: z
        .literal('confirmation_resolved')
        .describe('A confirmation request was resolved by a human decision (FEAT-019).'),
      confirmation_id: z.string().min(1).describe('ULID of the resolved request.'),
      decision: z.enum(['granted', 'denied', 'timed_out']).describe('Outcome of the confirmation.'),
      decided_by: z
        .enum(['user_interactive', 'user_cli_confirm', 'timeout'])
        .describe('Who or what resolved the confirmation — never agent.'),
    }),
    z.object({
      ...TaskEventBase,
      kind: z
        .literal('discovery_cycle_completed')
        .describe('One discovery propose→act→observe cycle finished (FEAT-020).'),
      cycle: DiscoveryCycle.describe('The completed cycle record.'),
    }),
    z.object({
      ...TaskEventBase,
      kind: z
        .literal('discovery_session_completed')
        .describe('A discovery session reached a terminal outcome (FEAT-020).'),
      outcome: DiscoveryOutcome.describe('Terminal outcome of the session.'),
      cycles: z.number().int().nonnegative().describe('Total cycles executed.'),
      promoted_workflow: z
        .string()
        .nullable()
        .describe('Workflow name if promoted via --save-as, or null.'),
    }),
  ])
  .describe('Discriminated union for task lifecycle events.');

export type TaskEvent = z.infer<typeof TaskEvent>;
